spring.datasource.url=${APP_DATABASE_URL}
spring.datasource.username=${APP_DATABASE_USER}
spring.datasource.password=${APP_DATABASE_PASSWORD}
spring.datasource.hikari.maximum-pool-size=16
spring.datasource.hikari.connection-timeout=5000
spring.datasource.hikari.connection-init-sql=SET statement_timeout = '10s'
spring.flyway.enabled=true
